services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"

  api:
    build: ./api
    restart: unless-stopped
    volumes:
      - ./api/src:/app/src
      - ./api/model:/app/model
      - ./api/server.js:/app/server.js
    env_file: # this is new
      - .env # this is new
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
        - action: rebuild
          path: ./backend/package.json

  database:
    image: mariadb:10.6
    restart: unless-stopped
    ports:
      # Make the DB accessible from outside of the Docker network if needed
      - 3307:3306
    volumes:
      # Mount a volume for mariadb's persistent files for lifecylce outside of stack
      - "./database/data:/var/lib/mysql"
      # Mount the db_schema directory into the container to be auto-read and created in the new db
      - "./database/db_schema:/docker-entrypoint-initdb.d"
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: ./database/db_schema/fitness_track_db.sql
  
  adminer:
    image: adminer
    ports: 
      - '${DB_WEB_PORT:?error}:8080'
    environment:
      ADMINER_DEFAULT_SERVER: 'database:${DB_PORT}'

  frontend:
    build: ./frontend
    restart: unless-stopped
    volumes:
      - ./frontend/src:/app/src
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
        - action: rebuild
          path: ./frontend/package.json
